{
 "title": "Private Broadcast Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Mempool size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mempool_size", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "targets": [
    { "expr": "blocks", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "memused", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Onion connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "onionpeers", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "IPv4 connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "ipv4peers", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}